# Generated by Django 5.2.15 on 2026-07-04 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('preparatory_meeting', 'Rendez-vous préparatoire'), ('confirmed', 'Confirmé'), ('performed', 'Presté'), ('paid', 'Payé'), ('cancelled', 'Annulé')], default='preparatory_meeting', max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_required', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_paid', models.BooleanField(default=False)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='accounts.clientprofile')),
                ('dj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='accounts.djprofile')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.eventtype')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.package')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='playlist', to='bookings.booking')),
                ('main_style', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.musicstyle')),
            ],
            options={
                'db_table': 'playlists',
            },
        ),
        migrations.CreateModel(
            name='PlaylistSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('artist', models.CharField(max_length=120)),
                ('preference_level', models.CharField(choices=[('must_play', 'À jouer absolument'), ('play_if_possible', 'À jouer si possible'), ('do_not_play', 'À ne pas jouer')], default='play_if_possible', max_length=30)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='bookings.playlist')),
            ],
            options={
                'db_table': 'playlist_songs',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration_hours', models.DecimalField(decimal_places=1, max_digits=4)),
                ('guest_count', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyé'), ('accepted', 'Accepté'), ('refused', 'Refusé')], default='draft', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('travel_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='accounts.clientprofile')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.eventtype')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.package')),
                ('selected_options', models.ManyToManyField(blank=True, related_name='quotes', to='catalog.serviceoption')),
            ],
            options={
                'db_table': 'quotes',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='quote',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='bookings.quote'),
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('street', models.CharField(max_length=160)),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=80)),
                ('country', models.CharField(default='Belgique', max_length=80)),
                ('has_parking', models.BooleanField(default=False)),
                ('distance_km_from_base', models.DecimalField(decimal_places=2, max_digits=6)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='accounts.clientprofile')),
            ],
            options={
                'db_table': 'venues',
            },
        ),
        migrations.AddField(
            model_name='quote',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookings.venue'),
        ),
        migrations.AddField(
            model_name='booking',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookings.venue'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('dj', 'event_date', 'start_time'), name='unique_confirmed_dj_slot'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='booking_end_after_start'),
        ),
    ]
