# Generated by Django 5.2.15 on 2026-07-08 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_clientprofile_options_alter_djprofile_options_and_more'),
        ('bookings', '0001_initial'),
        ('catalog', '0002_equipment_alter_eventtype_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='quantité')),
            ],
            options={
                'verbose_name': 'matériel de réservation',
                'verbose_name_plural': 'matériel de réservation',
                'db_table': 'booking_equipment',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=40, unique=True, verbose_name='numéro de contrat')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyé'), ('signed', 'Signé'), ('cancelled', 'Annulé')], default='draft', max_length=20, verbose_name='statut')),
                ('refund_policy', models.CharField(max_length=255, verbose_name='modalités de remboursement')),
                ('signed_by_client_at', models.DateTimeField(blank=True, null=True, verbose_name='signé par le client le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
            ],
            options={
                'verbose_name': 'contrat',
                'verbose_name_plural': 'contrats',
                'db_table': 'contracts',
            },
        ),
        migrations.CreateModel(
            name='PreparatoryAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(verbose_name='date et heure du rendez-vous')),
                ('mode', models.CharField(choices=[('online', 'En ligne'), ('in_person', 'En présentiel')], default='online', max_length=20, verbose_name='mode')),
                ('status', models.CharField(choices=[('planned', 'Planifié'), ('done', 'Réalisé'), ('cancelled', 'Annulé')], default='planned', max_length=20, verbose_name='statut')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'rendez-vous préparatoire',
                'verbose_name_plural': 'rendez-vous préparatoires',
                'db_table': 'preparatory_appointments',
            },
        ),
        migrations.CreateModel(
            name='QuoteOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prix unitaire')),
            ],
            options={
                'verbose_name': 'option de devis',
                'verbose_name_plural': 'options de devis',
                'db_table': 'quote_options',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='note')),
                ('comment', models.CharField(max_length=255, verbose_name='commentaire')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('published', 'Publié'), ('rejected', 'Rejeté')], default='pending', max_length=20, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
            ],
            options={
                'verbose_name': 'avis client',
                'verbose_name_plural': 'avis clients',
                'db_table': 'reviews',
            },
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'réservation', 'verbose_name_plural': 'réservations'},
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'verbose_name': 'playlist', 'verbose_name_plural': 'playlists'},
        ),
        migrations.AlterModelOptions(
            name='playlistsong',
            options={'verbose_name': 'chanson de playlist', 'verbose_name_plural': 'chansons de playlist'},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'verbose_name': 'devis', 'verbose_name_plural': 'devis'},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'verbose_name': 'lieu', 'verbose_name_plural': 'lieux'},
        ),
        migrations.RemoveField(
            model_name='quote',
            name='selected_options',
        ),
        migrations.AddField(
            model_name='playlistsong',
            name='status',
            field=models.CharField(choices=[('requested', 'Demandée'), ('approved', 'Acceptée'), ('rejected', 'Refusée')], default='requested', max_length=20, verbose_name='statut'),
        ),
        migrations.AddField(
            model_name='quote',
            name='distance_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='distance en km'),
        ),
        migrations.AddField(
            model_name='quote',
            name='parking_available',
            field=models.BooleanField(default=False, verbose_name='parking disponible'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name="motif d'annulation"),
        ),
        migrations.AlterField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='accounts.clientprofile', verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='deposit_paid',
            field=models.BooleanField(default=False, verbose_name='acompte payé'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='deposit_required',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='acompte requis'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='dj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='accounts.djprofile', verbose_name='DJ'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(verbose_name='heure de fin'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='event_date',
            field=models.DateField(verbose_name="date de l'événement"),
        ),
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.eventtype', verbose_name="type d'événement"),
        ),
        migrations.AlterField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.package', verbose_name='package'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='quote',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='bookings.quote', verbose_name='devis'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(verbose_name='heure de début'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('preparatory_meeting', 'Rendez-vous préparatoire'), ('confirmed', 'Confirmé'), ('performed', 'Presté'), ('paid', 'Payé'), ('cancelled', 'Annulé')], default='preparatory_meeting', max_length=30, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant total'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookings.venue', verbose_name='lieu'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='playlist', to='bookings.booking', verbose_name='réservation'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='main_style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.musicstyle', verbose_name='style principal'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='notes',
            field=models.CharField(blank=True, max_length=255, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='playlistsong',
            name='artist',
            field=models.CharField(max_length=120, verbose_name='artiste'),
        ),
        migrations.AlterField(
            model_name='playlistsong',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='bookings.playlist', verbose_name='playlist'),
        ),
        migrations.AlterField(
            model_name='playlistsong',
            name='preference_level',
            field=models.CharField(choices=[('must_play', 'À jouer absolument'), ('play_if_possible', 'À jouer si possible'), ('do_not_play', 'À ne pas jouer')], default='play_if_possible', max_length=30, verbose_name='préférence'),
        ),
        migrations.AlterField(
            model_name='playlistsong',
            name='title',
            field=models.CharField(max_length=160, verbose_name='titre'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='accounts.clientprofile', verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="montant de l'acompte"),
        ),
        migrations.AlterField(
            model_name='quote',
            name='duration_hours',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='durée en heures'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='event_date',
            field=models.DateField(verbose_name="date de l'événement"),
        ),
        migrations.AlterField(
            model_name='quote',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.eventtype', verbose_name="type d'événement"),
        ),
        migrations.AlterField(
            model_name='quote',
            name='guest_count',
            field=models.PositiveSmallIntegerField(verbose_name="nombre d'invités"),
        ),
        migrations.AlterField(
            model_name='quote',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.package', verbose_name='package'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='start_time',
            field=models.TimeField(verbose_name='heure de début'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyé'), ('accepted', 'Accepté'), ('refused', 'Refusé'), ('expired', 'Expiré')], default='draft', max_length=20, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='sous-total'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='montant total'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='travel_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='frais de déplacement'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookings.venue', verbose_name='lieu'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='city',
            field=models.CharField(max_length=80, verbose_name='ville'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='accounts.clientprofile', verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='country',
            field=models.CharField(default='Belgique', max_length=80, verbose_name='pays'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='distance_km_from_base',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='distance depuis la base (km)'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='has_parking',
            field=models.BooleanField(default=False, verbose_name='parking disponible'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=120, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='postal_code',
            field=models.CharField(max_length=20, verbose_name='code postal'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='street',
            field=models.CharField(max_length=160, verbose_name='rue'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['event_date'], name='idx_quote_event_date'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['status'], name='idx_quote_status'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['city'], name='idx_venue_city'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='quote_total_positive'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.CheckConstraint(condition=models.Q(('deposit_amount__gte', 0)), name='quote_deposit_positive'),
        ),
        migrations.AddConstraint(
            model_name='venue',
            constraint=models.CheckConstraint(condition=models.Q(('distance_km_from_base__gte', 0)), name='venue_distance_positive'),
        ),
        migrations.AddField(
            model_name='bookingequipment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking', verbose_name='réservation'),
        ),
        migrations.AddField(
            model_name='bookingequipment',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.equipment', verbose_name='matériel'),
        ),
        migrations.AddField(
            model_name='booking',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='bookings', through='bookings.BookingEquipment', to='catalog.equipment', verbose_name='matériel'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='booking_total_positive'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('deposit_required__gte', 0)), name='booking_deposit_positive'),
        ),
        migrations.AddField(
            model_name='contract',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='bookings.booking', verbose_name='réservation'),
        ),
        migrations.AddField(
            model_name='preparatoryappointment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='bookings.booking', verbose_name='réservation'),
        ),
        migrations.AddField(
            model_name='quoteoption',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='bookings.quote', verbose_name='devis'),
        ),
        migrations.AddField(
            model_name='quoteoption',
            name='service_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_options', to='catalog.serviceoption', verbose_name='option'),
        ),
        migrations.AddField(
            model_name='review',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bookings.booking', verbose_name='réservation'),
        ),
        migrations.AddField(
            model_name='review',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='accounts.clientprofile', verbose_name='client'),
        ),
        migrations.AddField(
            model_name='review',
            name='dj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='accounts.djprofile', verbose_name='DJ'),
        ),
        migrations.AddConstraint(
            model_name='bookingequipment',
            constraint=models.UniqueConstraint(fields=('booking', 'equipment'), name='unique_booking_equipment'),
        ),
        migrations.AddConstraint(
            model_name='bookingequipment',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='booking_equipment_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='quoteoption',
            constraint=models.UniqueConstraint(fields=('quote', 'service_option'), name='unique_quote_service_option'),
        ),
        migrations.AddConstraint(
            model_name='quoteoption',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='quote_option_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='quoteoption',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='quote_option_unit_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='review_rating_between_1_and_5'),
        ),
    ]
