# Generated by Django 5.2.15 on 2026-07-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_bookingequipment_contract_preparatoryappointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='music_preferences',
            field=models.TextField(blank=True, verbose_name='préférences musicales'),
        ),
    ]
