# Generated by Django 5.2.15 on 2026-08-04 10:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_quote_music_preferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255, verbose_name='motif')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Acceptée'), ('rejected', 'Refusée')], default='pending', max_length=20, verbose_name='statut')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='demandée le')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='traitée le')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_requests', to='bookings.booking', verbose_name='réservation')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_cancellation_requests', to=settings.AUTH_USER_MODEL, verbose_name='traitée par')),
            ],
            options={
                'verbose_name': "demande d'annulation",
                'verbose_name_plural': "demandes d'annulation",
                'db_table': 'cancellation_requests',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status', 'requested_at'], name='idx_cancel_request_status')],
            },
        ),
    ]
