# Generated by Django 5.2.15 on 2026-08-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_cancellationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellationrequest',
            name='review_message',
            field=models.CharField(blank=True, max_length=255, verbose_name='réponse administrative'),
        ),
    ]
