# Generated by Django 5.2.15 on 2026-08-20 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_djapplication'),
        ('bookings', '0006_booking_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='dj_decided_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='décision du DJ le'),
        ),
        migrations.AddField(
            model_name='quote',
            name='dj_decision',
            field=models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('refused', 'Refusée')], default='pending', max_length=20, verbose_name='décision du DJ'),
        ),
        migrations.AddField(
            model_name='quote',
            name='requested_dj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quote_requests', to='accounts.djprofile', verbose_name='DJ demandé'),
        ),
    ]
