# Generated by Django 5.2.15 on 2026-10-08 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_review_multiple_per_booking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=2000, verbose_name='message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='envoyé le')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='lu le')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bookings.booking', verbose_name='réservation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_messages', to=settings.AUTH_USER_MODEL, verbose_name='expéditeur')),
            ],
            options={
                'verbose_name': 'message de dossier',
                'verbose_name_plural': 'messages de dossier',
                'db_table': 'booking_messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['booking', 'created_at'], name='idx_message_booking_created')],
            },
        ),
    ]
