# Generated by Django 5.2.15 on 2026-10-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_communication_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='dj_responded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='réponse du DJ le'),
        ),
        migrations.AddField(
            model_name='review',
            name='dj_response',
            field=models.CharField(blank=True, max_length=255, verbose_name='réponse du DJ'),
        ),
        migrations.AddField(
            model_name='review',
            name='report_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='motif du signalement'),
        ),
        migrations.AddField(
            model_name='review',
            name='reported_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='signalé le'),
        ),
    ]
