# Generated by Django 5.2.15 on 2026-07-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=60, verbose_name='catégorie')),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('serial_number', models.CharField(max_length=80, unique=True, verbose_name='numéro de série')),
                ('daily_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='coût journalier')),
                ('replacement_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valeur de remplacement')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('maintenance', 'En maintenance'), ('reserved', 'Réservé')], default='available', max_length=20, verbose_name='statut')),
            ],
            options={
                'verbose_name': 'matériel',
                'verbose_name_plural': 'matériel',
                'db_table': 'equipment',
            },
        ),
        migrations.AlterModelOptions(
            name='eventtype',
            options={'verbose_name': "type d'événement", 'verbose_name_plural': "types d'événements"},
        ),
        migrations.AlterModelOptions(
            name='musicstyle',
            options={'verbose_name': 'style musical', 'verbose_name_plural': 'styles musicaux'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'verbose_name': 'package', 'verbose_name_plural': 'packages'},
        ),
        migrations.AlterModelOptions(
            name='serviceoption',
            options={'verbose_name': 'option de service', 'verbose_name_plural': 'options de service'},
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='name',
            field=models.CharField(max_length=80, unique=True, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='requires_preparatory_meeting',
            field=models.BooleanField(default=False, verbose_name='rendez-vous préparatoire requis'),
        ),
        migrations.AlterField(
            model_name='musicstyle',
            name='name',
            field=models.CharField(max_length=80, unique=True, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='package',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prix de base'),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.CharField(max_length=255, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='package',
            name='included_hours',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='heures incluses'),
        ),
        migrations.AlterField(
            model_name='package',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='actif'),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='serviceoption',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='actif'),
        ),
        migrations.AlterField(
            model_name='serviceoption',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='serviceoption',
            name='price_type',
            field=models.CharField(choices=[('fixed', 'Forfait'), ('hourly', 'Horaire')], default='fixed', max_length=20, verbose_name='type de prix'),
        ),
        migrations.AlterField(
            model_name='serviceoption',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prix unitaire'),
        ),
        migrations.AddConstraint(
            model_name='package',
            constraint=models.CheckConstraint(condition=models.Q(('base_price__gte', 0)), name='package_base_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='package',
            constraint=models.CheckConstraint(condition=models.Q(('included_hours__gt', 0)), name='package_included_hours_positive'),
        ),
        migrations.AddConstraint(
            model_name='serviceoption',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='service_option_unit_price_positive'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['category', 'status'], name='idx_equipment_category_status'),
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.CheckConstraint(condition=models.Q(('daily_cost__gte', 0)), name='equipment_daily_cost_positive'),
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.CheckConstraint(condition=models.Q(('replacement_value__gte', 0)), name='equipment_replacement_value_positive'),
        ),
    ]
