from django.db import migrations


WORLD_MUSIC_STYLES = (
    "Acid house",
    "Afro house",
    "Afrobeat",
    "Amapiano",
    "Ambient",
    "Arabic pop",
    "Bachata",
    "Balkan",
    "Baroque",
    "Bhangra",
    "Bikutsi",
    "Bluegrass",
    "Blues",
    "Bollywood",
    "Bossa nova",
    "Breakbeat",
    "Britpop",
    "Calypso",
    "Cantopop",
    "Carnatic",
    "Celtic",
    "Chaâbi",
    "Chanson française",
    "Chill-out",
    "City pop",
    "Classical",
    "Country",
    "Cumbia",
    "Coupé-décalé",
    "Dance",
    "Dangdut",
    "Deep house",
    "Disco",
    "Drill",
    "Drum and bass",
    "Dub",
    "Dubstep",
    "EDM",
    "Enka",
    "Fado",
    "Film music",
    "Flamenco",
    "Folk",
    "Forró",
    "Funk",
    "Future bass",
    "Gamelan",
    "Garage rock",
    "Gospel",
    "Gnawa",
    "Grime",
    "Hard rock",
    "Hardcore",
    "Hardstyle",
    "Heavy metal",
    "Highlife",
    "Indian classical",
    "Indie pop",
    "Indie rock",
    "J-pop",
    "Jazz",
    "Jungle",
    "K-pop",
    "Kizomba",
    "Klezmer",
    "Kompa",
    "Kuduro",
    "Latin jazz",
    "Latin pop",
    "Lo-fi hip-hop",
    "Makossa",
    "Mbalax",
    "Mandopop",
    "Merengue",
    "Metalcore",
    "Minimal techno",
    "Musical theatre",
    "Ndombolo",
    "Neo soul",
    "New wave",
    "Opera",
    "Oriental",
    "Polka",
    "Pop rock",
    "Progressive house",
    "Psytrance",
    "Punk rock",
    "Qawwali",
    "Raï",
    "Rap",
    "Reggae",
    "Reggaeton",
    "Rock",
    "Rock alternatif",
    "Rock and roll",
    "Romantic classical",
    "Salsa",
    "Samba",
    "Ska",
    "Soca",
    "Soul",
    "Soukous",
    "Synthpop",
    "Tango",
    "Tarab",
    "Tech house",
    "Trance",
    "Trap",
    "Trip-hop",
    "Trot",
    "UK garage",
    "World music",
    "Zouk",
)


def add_world_music_styles(apps, schema_editor):
    music_style = apps.get_model("catalog", "MusicStyle")
    existing_names = set(music_style.objects.values_list("name", flat=True))
    music_style.objects.bulk_create(
        [music_style(name=name) for name in WORLD_MUSIC_STYLES if name not in existing_names],
    )


class Migration(migrations.Migration):
    dependencies = [("catalog", "0006_require_preparatory_meetings")]

    operations = [
        migrations.RunPython(add_world_music_styles, migrations.RunPython.noop),
    ]
