# Generated by Django 5.2.15 on 2026-07-04 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DJAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Réservé'), ('blocked', 'Bloqué')], default='available', max_length=20)),
                ('dj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='accounts.djprofile')),
            ],
            options={
                'db_table': 'dj_availabilities',
                'indexes': [models.Index(fields=['available_date', 'status'], name='dj_availabi_availab_7a0aee_idx')],
                'constraints': [models.UniqueConstraint(fields=('dj', 'available_date', 'start_time'), name='unique_dj_availability_slot'), models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='availability_end_after_start')],
            },
        ),
    ]
