# Generated by Django 5.2.15 on 2026-07-08 06:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_clientprofile_options_alter_djprofile_options_and_more'),
        ('availability', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='djavailability',
            options={'verbose_name': 'créneau DJ', 'verbose_name_plural': 'créneaux DJ'},
        ),
        migrations.RenameIndex(
            model_name='djavailability',
            new_name='idx_availability_search',
            old_name='dj_availabi_availab_7a0aee_idx',
        ),
        migrations.AddField(
            model_name='djavailability',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='créé le'),
        ),
        migrations.AddField(
            model_name='djavailability',
            name='reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='motif'),
        ),
        migrations.AlterField(
            model_name='djavailability',
            name='available_date',
            field=models.DateField(verbose_name='date disponible'),
        ),
        migrations.AlterField(
            model_name='djavailability',
            name='dj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='accounts.djprofile', verbose_name='DJ'),
        ),
        migrations.AlterField(
            model_name='djavailability',
            name='end_time',
            field=models.TimeField(verbose_name='heure de fin'),
        ),
        migrations.AlterField(
            model_name='djavailability',
            name='start_time',
            field=models.TimeField(verbose_name='heure de début'),
        ),
        migrations.AlterField(
            model_name='djavailability',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Réservé'), ('blocked', 'Bloqué')], default='available', max_length=20, verbose_name='statut'),
        ),
    ]
