# Generated by Django 5.2.15 on 2026-08-20 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0003_djavailability_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djavailability',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Réservé'), ('occupied', 'Occupé'), ('blocked', 'Bloqué')], default='available', max_length=20, verbose_name='statut'),
        ),
    ]
