# Generated by Django 5.2.15 on 2026-07-04 15:52

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_language', models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais'), ('nl', 'Néerlandais')], default='fr', max_length=5)),
                ('date_of_birth', models.DateField(validators=[apps.accounts.models.validate_adult])),
                ('phone', models.CharField(max_length=30)),
                ('billing_address', models.CharField(max_length=255)),
                ('billing_city', models.CharField(max_length=80)),
                ('billing_postal_code', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client_profiles',
            },
        ),
        migrations.CreateModel(
            name='DJProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=100, unique=True)),
                ('bio', models.TextField()),
                ('base_hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('travel_rate_per_km', models.DecimalField(decimal_places=2, default=0.6, max_digits=10)),
                ('years_experience', models.PositiveSmallIntegerField(default=1)),
                ('is_available', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dj_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dj_profiles',
            },
        ),
    ]
