# Generated by Django 5.2.15 on 2026-07-08 06:39

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0002_equipment_alter_eventtype_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientprofile',
            options={'verbose_name': 'profil client', 'verbose_name_plural': 'profils clients'},
        ),
        migrations.AlterModelOptions(
            name='djprofile',
            options={'verbose_name': 'profil DJ', 'verbose_name_plural': 'profils DJ'},
        ),
        migrations.AddField(
            model_name='djprofile',
            name='music_styles',
            field=models.ManyToManyField(blank=True, related_name='djs', to='catalog.musicstyle', verbose_name='styles musicaux'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='billing_address',
            field=models.CharField(max_length=255, verbose_name='adresse de facturation'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='billing_city',
            field=models.CharField(max_length=80, verbose_name='ville de facturation'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='billing_postal_code',
            field=models.CharField(max_length=20, verbose_name='code postal de facturation'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='créé le'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='date_of_birth',
            field=models.DateField(validators=[apps.accounts.models.validate_adult], verbose_name='date de naissance'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='téléphone'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='preferred_language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais'), ('nl', 'Néerlandais')], default='fr', max_length=5, verbose_name='langue préférée'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AlterField(
            model_name='djprofile',
            name='base_hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='tarif horaire de base'),
        ),
        migrations.AlterField(
            model_name='djprofile',
            name='bio',
            field=models.TextField(verbose_name='biographie'),
        ),
        migrations.AlterField(
            model_name='djprofile',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='disponible'),
        ),
        migrations.AlterField(
            model_name='djprofile',
            name='stage_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='nom de scène'),
        ),
        migrations.AlterField(
            model_name='djprofile',
            name='travel_rate_per_km',
            field=models.DecimalField(decimal_places=2, default=0.6, max_digits=10, verbose_name='tarif de déplacement par km'),
        ),
        migrations.AlterField(
            model_name='djprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dj_profile', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AlterField(
            model_name='djprofile',
            name='years_experience',
            field=models.PositiveSmallIntegerField(default=1, verbose_name="années d'expérience"),
        ),
        migrations.AddIndex(
            model_name='clientprofile',
            index=models.Index(fields=['billing_city'], name='idx_client_city'),
        ),
        migrations.AddIndex(
            model_name='djprofile',
            index=models.Index(fields=['is_available'], name='idx_dj_available'),
        ),
        migrations.AddConstraint(
            model_name='djprofile',
            constraint=models.CheckConstraint(condition=models.Q(('base_hourly_rate__gte', 0)), name='dj_base_hourly_rate_positive'),
        ),
        migrations.AddConstraint(
            model_name='djprofile',
            constraint=models.CheckConstraint(condition=models.Q(('travel_rate_per_km__gte', 0)), name='dj_travel_rate_positive'),
        ),
    ]
