# Generated by Django 5.2.15 on 2026-08-04 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_clientprofile_options_alter_djprofile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='motif')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Refusée'), ('cancelled', 'Annulée par le client')], default='pending', max_length=20, verbose_name='statut')),
                ('review_message', models.TextField(blank=True, verbose_name='réponse administrative')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='demandée le')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='traitée le')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deletion_requests', to='accounts.clientprofile', verbose_name='client')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_account_deletion_requests', to=settings.AUTH_USER_MODEL, verbose_name='traitée par')),
            ],
            options={
                'verbose_name': 'demande de suppression de compte',
                'verbose_name_plural': 'demandes de suppression de compte',
                'db_table': 'account_deletion_requests',
                'ordering': ['-requested_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('client',), name='unique_pending_account_deletion')],
            },
        ),
    ]
