# Generated by Django 5.2.15 on 2026-08-04 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accountdeletionrequest'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='accountdeletionrequest',
            name='unique_pending_account_deletion',
        ),
    ]
