# Generated by Django 5.2.15 on 2026-08-17 19:34

import apps.accounts.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_accountdeletionrequest_unique_pending_account_deletion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DJApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=100, unique=True, verbose_name='nom de scène')),
                ('date_of_birth', models.DateField(validators=[apps.accounts.models.validate_adult], verbose_name='date de naissance')),
                ('phone', models.CharField(max_length=30, verbose_name='téléphone')),
                ('city', models.CharField(max_length=80, verbose_name='ville')),
                ('preferred_language', models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais'), ('nl', 'Néerlandais')], default='fr', max_length=5, verbose_name='langue préférée')),
                ('bio', models.TextField(verbose_name='présentation')),
                ('music_styles', models.CharField(max_length=255, verbose_name='styles musicaux')),
                ('base_hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='tarif horaire souhaité')),
                ('years_experience', models.PositiveSmallIntegerField(default=1, verbose_name="années d'expérience")),
                ('identity_document', models.FileField(upload_to='private/dj-applications/identity/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), apps.accounts.models.validate_application_file_size], verbose_name="pièce d'identité")),
                ('insurance_document', models.FileField(upload_to='private/dj-applications/insurance/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), apps.accounts.models.validate_application_file_size], verbose_name='assurance responsabilité civile')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Refusée')], default='pending', max_length=20, verbose_name='statut')),
                ('review_message', models.TextField(blank=True, verbose_name='réponse administrative')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='envoyée le')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='traitée le')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_dj_applications', to=settings.AUTH_USER_MODEL, verbose_name='traitée par')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dj_application', to=settings.AUTH_USER_MODEL, verbose_name='candidat')),
            ],
            options={
                'verbose_name': 'candidature DJ',
                'verbose_name_plural': 'candidatures DJ',
                'db_table': 'dj_applications',
                'ordering': ['-submitted_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('base_hourly_rate__gte', 0)), name='dj_application_rate_positive')],
            },
        ),
    ]
