# Generated by Django 5.2.15 on 2026-10-07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0005_djapplication"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("notification_type", models.CharField(choices=[("booking", "Dossier"), ("payment", "Paiement"), ("review", "Avis"), ("account", "Compte")], default="booking", max_length=20, verbose_name="type")),
                ("title", models.CharField(max_length=180, verbose_name="titre")),
                ("message", models.TextField(verbose_name="message")),
                ("link", models.CharField(blank=True, max_length=120, verbose_name="lien")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="créée le")),
                ("read_at", models.DateTimeField(blank=True, null=True, verbose_name="lue le")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notifications", to=settings.AUTH_USER_MODEL, verbose_name="destinataire")),
            ],
            options={"verbose_name": "notification", "verbose_name_plural": "notifications", "db_table": "account_notifications", "ordering": ["-created_at"]},
        ),
        migrations.AddIndex(model_name="notification", index=models.Index(fields=["user", "read_at", "created_at"], name="idx_notif_user_read_created")),
    ]
