# Generated by Django 5.2.15 on 2026-10-08 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='notifications e-mail')),
                ('internal_enabled', models.BooleanField(default=True, verbose_name="notifications dans l'application")),
                ('booking_enabled', models.BooleanField(default=True, verbose_name='alertes de dossier')),
                ('payment_enabled', models.BooleanField(default=True, verbose_name='alertes de paiement')),
                ('review_enabled', models.BooleanField(default=True, verbose_name="alertes d'avis")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'préférence de notification',
                'verbose_name_plural': 'préférences de notification',
                'db_table': 'notification_preferences',
            },
        ),
    ]
