# Generated by Django 5.2.15 on 2026-07-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_invoice_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=190, null=True, unique=True, verbose_name="identifiant d'intention de paiement Stripe"),
        ),
    ]
