# Generated by Django 5.2.15 on 2026-08-04 10:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_stripe_payment_intent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_refund_id', models.CharField(blank=True, max_length=190, null=True, unique=True, verbose_name='identifiant de remboursement Stripe')),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="clé d'idempotence")),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='devise')),
                ('reason', models.CharField(choices=[('requested_by_customer', 'Demandé par le client'), ('duplicate', 'Paiement en double'), ('fraudulent', 'Paiement frauduleux')], default='requested_by_customer', max_length=40, verbose_name='raison Stripe')),
                ('internal_reason', models.CharField(max_length=255, verbose_name='motif interne')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('succeeded', 'Réussi'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='traité le')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment', verbose_name='paiement')),
            ],
            options={
                'verbose_name': 'remboursement',
                'verbose_name_plural': 'remboursements',
                'db_table': 'refunds',
                'indexes': [models.Index(fields=['status', 'created_at'], name='idx_refund_status_created')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='refund_amount_positive')],
            },
        ),
    ]
