# Generated by Django 5.2.15 on 2026-10-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='last_payment_reminder_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='dernier rappel de paiement'),
        ),
    ]
