# Generated by Django 5.2.15 on 2026-10-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_invoice_last_payment_reminder_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='privacy_policy_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='politique de confidentialité acceptée le'),
        ),
        migrations.AddField(
            model_name='payment',
            name='privacy_policy_version',
            field=models.CharField(blank=True, max_length=32, verbose_name='version de la politique acceptée'),
        ),
    ]
